name = "WordGraphs"
uuid = "1b0b0e52-fe23-4275-8ccb-42ed58001e55"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.0.1"

[deps]

SimpleGraphs = "55797a34-41de-5266-9ec1-32ac4eb504d3"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[compat]

SimpleGraphs = "0.7"
Combinatorics = "1"
